services:
  postgres:
    image: postgres:16-alpine
    container_name: devboard-postgres
    environment:
      POSTGRES_DB: devboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devboard-api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=devboard;Username=postgres;Password=postgres"
      JwtSettings__SecretKey: "soy-cacho-de-buenos-aires-y-tengo-1-sueño-escondido"
      JwtSettings__Issuer: "DevBoard"
      JwtSettings__Audience: "DevBoard"
      JwtSettings__ExpirationMinutes: "60"
      JwtSettings__RefreshTokenExpirationDays: "7"
      CorsSettings__AllowedOrigins: "http://localhost:4200"
    ports:
      - "5000:8080"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ../devboard-frontend
      dockerfile: Dockerfile
    container_name: devboard-frontend
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  postgres_data: